16.0 fix resize chart mamu
odoo/o-spreadsheet pull request #1757
Opened 2022-10-26 12:17 UTC by mamu-odoo

## Description:

Add a maximum to deltaX and deltaY to prevent the figure from moving.

Odoo task ID : [TASK_ID](https://www.odoo.com/web#cids=1&menu_id=5879&action=333&active_id=2328&model=project.task&view_type=form&id=3044939)

## review checklist

- [ ] feature is organized in plugin, or UI components
- [ ] support of duplicate sheet (deep copy)
- [ ] in model/core: ranges are Range object, and can be adapted (adaptRanges)
- [ ] in model/UI: ranges are strings (to show the user)
- [ ] undo-able commands (uses this.history.update)
- [ ] multiuser-able commands (has inverse commands and transformations where needed)
- [ ] new/updated/removed commands are documented
- [ ] exportable in excel
- [ ] translations (\_lt("qmsdf %s", abc))
- [ ] unit tested
- [ ] clean commented code
- [ ] track breaking changes
- [ ] doc is rebuild (npm run doc)
- [ ] status is correct in Odoo

2022-10-26 12:18 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/o-spreadsheet/pull/1757).

2022-10-26 13:26 UTC, LucasLefevre commented on src/components/figures/figure/figure.ts
> +      const deltaY = Math.max(dirY * (ev.clientY - initialY), MIN_FIG_SIZE - figure.height);
Then the two `Math.max` below are useless and can be removed

2022-11-23 14:33 UTC, pro-odoo requested changes
Ok except the two little comments :)

2022-11-23 14:33 UTC, pro-odoo commented on tests/components/figure.test.ts
> +  top: ".o-anchor.o-top",
top, right, bottom and left are not necessary. If we add them, we will have to maintain it for no reason.

2022-11-23 14:33 UTC, pro-odoo commented on src/components/figures/figure/figure.ts
> +export const MIN_FIG_SIZE = 80;
As we have to export it, I would move it to `constants.ts`

2022-11-28 08:43 UTC, pro-odoo commented on tests/components/figure.test.ts
> +  top: ".o-anchor.o-top",
This comment is marked as resolved but without changes nor explanation. Is it intended ?

2022-11-28 09:01 UTC, pro-odoo approved these changes
robodoo r+

2022-11-28 09:09 UTC, closed without merging