[IMP] spreadsheet: Index function
odoo/o-spreadsheet pull request #1840
Opened 2022-11-30 12:06 UTC by mamu-odoo

## Description:

Partially implemented the ['Index(reference, [row], [column])](https://support.google.com/docs/answer/3098242?hl=en).
Currently the task is blocked because it requires  "multicell" of the task [3018032](https://www.odoo.com/web#id=3018032&cids=1&menu_id=4720&action=333&active_id=2328&model=project.task&view_type=form).

Odoo task ID : [2871406](https://www.odoo.com/web#id=2871406&action=333&active_id=2328&model=project.task&view_type=form&cids=1&menu_id=4720)

## review checklist

- [ ] feature is organized in plugin, or UI components
- [ ] support of duplicate sheet (deep copy)
- [ ] in model/core: ranges are Range object, and can be adapted (adaptRanges)
- [ ] in model/UI: ranges are strings (to show the user)
- [ ] undo-able commands (uses this.history.update)
- [ ] multiuser-able commands (has inverse commands and transformations where needed)
- [ ] new/updated/removed commands are documented
- [ ] exportable in excel
- [ ] translations (\_lt("qmsdf %s", abc))
- [ ] unit tested
- [ ] clean commented code
- [ ] track breaking changes
- [ ] doc is rebuild (npm run doc)
- [ ] status is correct in Odoo

2022-11-30 12:06 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/o-spreadsheet/pull/1840).

2023-08-03 07:54 UTC, laa-odoo requested changes

2023-08-03 07:54 UTC, laa-odoo commented on src/functions/module_lookup.ts
> +    arg("reference (range)", _lt("The range of cells from which the values are returned.")),
Could be any too

2023-08-03 07:54 UTC, laa-odoo commented on src/functions/module_lookup.ts
> +      "row (number, optional, default=0)",
FYI Optional is not mandatory when default is present

2023-08-03 07:54 UTC, laa-odoo commented on src/functions/module_lookup.ts
> +      "column (number, optional, default=0)",
same here

2023-08-03 07:54 UTC, laa-odoo commented on src/functions/module_lookup.ts
> +  compute: function (reference: MatrixArgValue, row: number = 0, column: number = 0): any {
reference: ArgValue
row: PrimitiveArgValue = 0
column: PrimitiveArgValue = 0

return : FunctionReturnValue

2023-08-03 07:54 UTC, laa-odoo commented on src/functions/module_lookup.ts
> +  compute: function (reference: MatrixArgValue, row: number = 0, column: number = 0): any {
Need to apply the ```toNumber``` helper on ```row``` and ```column```. And use something like ```_row``` ```_column```  
in the rest of the function

2023-08-03 07:56 UTC, laa-odoo commented
all commits could be squashed :)

2023-08-04 14:41 UTC, laa-odoo approved these changes

2023-08-07 14:22 UTC, LucasLefevre reviewed
nice little function :)

2023-08-07 14:22 UTC, LucasLefevre commented on tests/functions/module_lookup.test.ts
> +  const defaultGrid = {
since is only used once, it can be in-lined where it's used

2023-08-08 12:14 UTC, LucasLefevre approved these changes
robodoo r+

2023-08-08 13:27 UTC, LucasLefevre reviewed
robodoo r+

2023-08-08 14:24 UTC, closed without merging