[REF/IMP] figure: refactor figure container and handle scroll
odoo/o-spreadsheet pull request #2005
Opened 2023-01-27 11:24 UTC by hokolomopo

## Description

This commit refactor the figure container and inverse viewport: now the figure don't have to create its own container and inverse viewport, but this is handled by the `FigureContainer`, that place the figures in the correct container.

There is a new container specific to the figure that is currently dragged. The container takes the full screen and is independent of the scroll of the spreadsheet. When we start the drag & drop, we transform the figure coordinates for this container, and we transform them back when we drop the figure. This allow us to not worry about the scroll and the frozen panes during the drag & drop.

Odoo task ID : [3035531](https://www.odoo.com/web#id=3035531&action=333&active_id=2328&model=project.task&view_type=form&cids=1&menu_id=4720)

## review checklist

- [ ] feature is organized in plugin, or UI components
- [ ] support of duplicate sheet (deep copy)
- [ ] in model/core: ranges are Range object, and can be adapted (adaptRanges)
- [ ] in model/UI: ranges are strings (to show the user)
- [ ] undo-able commands (uses this.history.update)
- [ ] multiuser-able commands (has inverse commands and transformations where needed)
- [ ] new/updated/removed commands are documented
- [ ] exportable in excel
- [ ] translations (\_lt("qmsdf %s", abc))
- [ ] unit tested
- [ ] clean commented code
- [ ] track breaking changes
- [ ] doc is rebuild (npm run doc)
- [ ] status is correct in Odoo

2023-01-27 11:25 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/o-spreadsheet/pull/2005).

2023-01-31 17:10 UTC, rrahir requested changes
:+1:  :100:  Really better now, I feel like we are going in the right direction with the next step being the menu fed as props to the figure so we can factorize a bit more.

I wonder if we could have a single function that creates a map with 
``` javascript 
{ 
  containerType:
  {
    figures: Figure[], 
    containerStyle: Style
  }
}
```
because the back-and-forth between the iteration of container and their style and then the figures in the container and then the update figure position (based on dnd) is not that easy to follow

2023-02-01 12:52 UTC, hokolomopo commented on src/components/figures/figure_container/figure_container.ts
> +    const { offsetX: scrollX, offsetY: scrollY } =
Added commit to refactor `getActiveSheetSCrollInfo()`

2023-02-01 13:07 UTC, hokolomopo commented on src/components/figures/figure_container/figure_container.ts
> +      const newX = ev.clientX - position.left;
Yeah the position looks useless now

2023-02-01 13:11 UTC, hokolomopo commented on src/helpers/figures/figure/figure.ts
> +export function internalToScreenCoordinates(
Yhea it probably don't need to be exposed. 

As for the name, idk.

2023-02-01 13:15 UTC, hokolomopo commented on src/components/figures/figure_container/figure_container.ts
> +    if (this.dnd.figId && !visibleFigures.find((figure) => figure.id === this.dnd.figId)) {
Let's win 0.0000001s ! Performance FTW

2023-02-01 13:16 UTC, hokolomopo commented on tests/components/figure.test.ts
> +          x: 16 * cellWidth + 1,
'cause we do a mousemove of 1px, duh.

2023-02-01 13:57 UTC, hokolomopo commented on src/types/figure.ts
> +export type ResizeDirection = -1 | 0 | 1;
I'll leave it as it because we do shortcuts like `delta = dirX * something`

2023-02-01 15:13 UTC, rrahir commented on src/components/figures/figure_container/figure_container.ts
> +  getContainers(): Container[] {
make it a getter ?

2023-02-01 15:13 UTC, rrahir commented on src/components/figures/figure_container/figure_container.ts
> +  getVisibleFigures(): Figure[] {
getVisibleFigures, getContainerStyle, getInverseViewportPositionStyle  are private internal functions

2023-02-03 08:31 UTC, rrahir commented
@robodoo r+

2023-02-03 09:00 UTC, robodoo commented
@hokolomopo @rrahir because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

2023-02-03 10:02 UTC, rrahir commented
@robodoo r+ rebase-ff

2023-02-03 10:03 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-02-03 10:09 UTC, closed without merging