[FIX] Chart Panel: Manage title state in side panel
odoo/o-spreadsheet pull request #2556
Opened 2023-06-06 06:42 UTC by jash-odoo

## Description:

Previously, when we updated the title of the chart in the side panel and clicked on a cell, the new value would be lost.

This PR addresses and resolves that issue.

Odoo task ID : [2991474](https://www.odoo.com/web#id=2991474&cids=2&menu_id=4720&action=333&active_id=2328&model=project.task&view_type=form)

## review checklist

- [ ] feature is organized in plugin, or UI components
- [ ] support of duplicate sheet (deep copy)
- [ ] in model/core: ranges are Range object, and can be adapted (adaptRanges)
- [ ] in model/UI: ranges are strings (to show the user)
- [ ] undo-able commands (uses this.history.update)
- [ ] multiuser-able commands (has inverse commands and transformations where needed)
- [ ] new/updated/removed commands are documented
- [ ] exportable in excel
- [ ] translations (\_lt("qmsdf %s", abc))
- [ ] unit tested
- [ ] clean commented code
- [ ] track breaking changes
- [ ] doc is rebuild (npm run doc)
- [ ] status is correct in Odoo

2023-06-06 06:43 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/o-spreadsheet/pull/2556).

2023-06-12 13:15 UTC, hokolomopo reviewed
Seems good :+1:

2023-06-12 13:15 UTC, hokolomopo commented on src/components/side_panel/chart/line_bar_pie_panel/design_panel.ts
> +      title: _t(this.state.title),
The translation should be at the setup, not here. 

The title of the chart might be translated (we extract chart titles for translation in dashboard), so translatting it at startup make sense. But the new title that the user just inputted will not be in the translation and even if it was a translatable string, we want to store the non-translated one in DB.

2023-06-13 12:36 UTC, rrahir requested changes
could you add a test for this fix please ?

2023-06-15 06:41 UTC, jash-odoo commented
Hello @rrahir I added the test for same, can you please review this again?

2023-06-15 07:27 UTC, rrahir requested changes

2023-06-15 07:27 UTC, rrahir commented on tests/components/charts.test.ts
> +      await nextTick();
you should check the current value first

2023-06-15 07:27 UTC, rrahir commented on tests/components/charts.test.ts
> +      setInputValueAndTrigger(".o-chart-title input", "new_title", "change");
In master, this specific line triggers the `updateTitle` method of the sidepanel which in turn updates the chart. This  means the test passes in master. you should remove it (which would make the test fail in master) and the see if your fix works

2023-06-20 06:09 UTC, rrahir approved these changes
Nice :)

@robodoo r+

2023-06-20 06:14 UTC, closed without merging