[FIX] TopBar: fix focus lost in grid
odoo/o-spreadsheet pull request #2691
Opened 2023-07-19 05:55 UTC by aath-odoo

## Description:

Fixed the focus is lost in the grid when clicking a menu-item in the topbar. Previously clicking a topbar menu-item loses the focus in grid, Now the focus is maintained within the grid after interacting with the menu.

Task: [3419397](https://www.odoo.com/web#id=3419397&menu_id=4720&cids=2&action=333&active_id=2328&model=project.task&view_type=form)

## review checklist

- [ ] feature is organized in plugin, or UI components
- [ ] support of duplicate sheet (deep copy)
- [ ] in model/core: ranges are Range object, and can be adapted (adaptRanges)
- [ ] in model/UI: ranges are strings (to show the user)
- [ ] undo-able commands (uses this.history.update)
- [ ] multiuser-able commands (has inverse commands and transformations where needed)
- [ ] new/updated/removed commands are documented
- [ ] exportable in excel
- [ ] translations (\_lt("qmsdf %s", abc))
- [ ] unit tested
- [ ] clean commented code
- [ ] track breaking changes
- [ ] doc is rebuild (npm run doc)
- [ ] status is correct in Odoo

2023-07-19 05:56 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/o-spreadsheet/pull/2691).

2023-07-20 09:38 UTC, somu-odoo requested changes
Looks good to me, just couple minor changes.

2023-07-20 09:38 UTC, somu-odoo commented on src/components/top_bar/top_bar.ts
> +
Not needed, instead simply use onMenuClicked props in Menu

```suggestion
```

2023-07-20 09:38 UTC, somu-odoo commented on src/components/top_bar/top_bar.xml
> +            onClose="() => this.onMenuClick()"
```suggestion
            onMenuClicked="() => this.props.onClick()"
            onClose="() => this.closeMenus()"
```

2023-07-20 09:38 UTC, somu-odoo commented on tests/components/spreadsheet.test.ts
> +
```suggestion
```

2023-07-20 09:38 UTC, somu-odoo commented on tests/components/spreadsheet.test.ts
> +  test("grid should regain focus on topbar menu click", async () => {
```suggestion
  test("grid should regain focus after a topbar menu option is selected", async () => {
```

2023-07-26 09:44 UTC, hokolomopo reviewed
@robodoo r+

2023-07-26 09:54 UTC, closed without merging