16.0 fix insert row data filter header dhrp
odoo/o-spreadsheet pull request #3031
Opened 2023-10-19 05:26 UTC by dhrp-odoo

## Description:

This PR includes two distinct commits that address issues related to the handling of data filter headers in our SheetPlugin and FilterEvaluationPlugin.

Commit 1: [FIX] FilterEvaluationPlugin: insert row on data filter header

- Previously, when inserting a row above or below a data filter header, hidden rows inside the data filter were not being updated. This caused a state inconsistency issue between the data filter header and the data filter values.
- This commit address the problem by ensuring that hidden rows inside the data filter header are correctly updated when rows are inserted above or below the data filter header.

Commit 2: [FIX] SheetPlugin: removing row with data filter header

- Previously, removing rows that included the filter header failed to remove the associated data filter tables.
- This commit addresses the issue by ensuring the data filter tables is also removed when rows with the filter header are deleted.

Task: : [3546012](https://www.odoo.com/web#id=3546012&action=333&active_id=2328&model=project.task&view_type=form&cids=1&menu_id=4720)

## review checklist

- [ ] feature is organized in plugin, or UI components
- [ ] support of duplicate sheet (deep copy)
- [ ] in model/core: ranges are Range object, and can be adapted (adaptRanges)
- [ ] in model/UI: ranges are strings (to show the user)
- [ ] undo-able commands (uses this.history.update)
- [ ] multiuser-able commands (has inverse commands and transformations where needed)
- [ ] new/updated/removed commands are documented
- [ ] exportable in excel
- [ ] translations (\_lt("qmsdf %s", abc))
- [ ] unit tested
- [ ] clean commented code
- [ ] track breaking changes
- [ ] doc is rebuild (npm run doc)
- [ ] status is correct in Odoo

2023-10-19 05:27 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/o-spreadsheet/pull/3031).

2023-11-01 17:10 UTC, rrahir requested changes

2023-11-01 17:10 UTC, rrahir commented on tests/plugins/filters.test.ts
> +        expect(model.getters.getFilterTables(sheetId).length).toEqual(0);
```suggestion
        expect(model.getters.getFilterTables(sheetId)).toEqual([]);
```

2023-11-01 17:10 UTC, rrahir commented on tests/plugins/filter_evaluation.test.ts
> +    addRows(model, "before", 0, 1);
for both tests ,check after/before and use the getter `isRowFiltered`, to ensure that it is the work of the filter itself.

2023-11-02 06:40 UTC, dhrp-odoo commented
Hello @rrahir, I've implemented the suggested changes. Thank you!

2023-11-02 07:13 UTC, rrahir commented
@robodoo r+

2023-11-02 08:00 UTC, robodoo commented
@dhrp-odoo @rrahir because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

2023-11-02 08:16 UTC, rrahir commented
@robodoo rebase-ff

2023-11-02 08:17 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2023-11-02 08:23 UTC, closed without merging