[IMP] xlsx: import/export scatter plot
odoo/o-spreadsheet pull request #3455
Opened 2024-01-17 08:42 UTC by anhe-odoo

## Description:

Following the add of scatter plot in o-spreadsheet, this PR aims to allow the user to import/export a scatter plot from/to an xlsx file.

## Related Task/PR :
- Task: : [3633445](https://www.odoo.com/web#id=3633445&action=333&active_id=2328&model=project.task&view_type=form&cids=1&menu_id=4720)
- https://github.com/odoo/o-spreadsheet/pull/3316

## review checklist

- [ ] feature is organized in plugin, or UI components
- [ ] support of duplicate sheet (deep copy)
- [ ] in model/core: ranges are Range object, and can be adapted (adaptRanges)
- [ ] in model/UI: ranges are strings (to show the user)
- [ ] undo-able commands (uses this.history.update)
- [ ] multiuser-able commands (has inverse commands and transformations where needed)
- [ ] new/updated/removed commands are documented
- [ ] exportable in excel
- [ ] translations (\_t("qmsdf %s", abc))
- [ ] unit tested
- [ ] clean commented code
- [ ] track breaking changes
- [ ] doc is rebuild (npm run doc)
- [ ] status is correct in Odoo

2024-01-17 08:43 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/o-spreadsheet/pull/3455).

2024-02-06 09:23 UTC, hokolomopo reviewed
I'd try to add a test for the import if possible. Otherwise, good work 👍

2024-04-06 07:51 UTC, rrahir commented on src/xlsx/extraction/chart_extractor.ts
>            labelRange: this.extractChildTextContent(rootChartElement, "c:ser c:cat c:f"),
this line also needs to be adapted. With the scatter chart, the label range is set as a `numRef` and not `cat` so the selector should be `c:ser c:numRef c:f`

2024-04-06 08:03 UTC, rrahir commented on tests/xlsx/xlsx_import.test.ts
> +    expect(chartData.dataSets).toEqual(["Sheet1!C26:C35"]);
Add a labelRange check

2024-04-06 08:05 UTC, rrahir requested changes
Just one remark :-)
I hope the rebase will be okay :'(

2024-04-08 10:34 UTC, anhe-odoo commented
@rrahir : Thanks for the comments :) It has been updated and should be okay

2024-04-09 14:26 UTC, rrahir commented
@robodoo r+

2024-04-09 14:47 UTC, closed without merging