[FIX] FigureComponent: Undo/Redo broken after pasting figure
odoo/o-spreadsheet pull request #3678
Opened 2024-02-13 07:18 UTC by dhrp-odoo

## Description:

Previously, the Undo/Redo functionality was broken after pasting a figure. This occurred because the focus remained on the pasted figure rather than on the grid or composer, where the key events for Undo/Redo are handled.

This commit resolves the issue by handling the key events directly on the figure component itself. With this change, Undo/Redo operations now work as expected even after pasting a figure.

Task: : [3659930](https://www.odoo.com/web#id=3659930&action=333&active_id=2328&model=project.task&view_type=form&cids=1&menu_id=4720)

## review checklist

- [ ] feature is organized in plugin, or UI components
- [ ] support of duplicate sheet (deep copy)
- [ ] in model/core: ranges are Range object, and can be adapted (adaptRanges)
- [ ] in model/UI: ranges are strings (to show the user)
- [ ] undo-able commands (uses this.history.update)
- [ ] multiuser-able commands (has inverse commands and transformations where needed)
- [ ] new/updated/removed commands are documented
- [ ] exportable in excel
- [ ] translations (\_t("qmsdf %s", abc))
- [ ] unit tested
- [ ] clean commented code
- [ ] track breaking changes
- [ ] doc is rebuild (npm run doc)
- [ ] status is correct in Odoo

2024-02-13 07:18 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/o-spreadsheet/pull/3678).

2024-02-26 13:31 UTC, dhrp-odoo commented on src/components/figures/figure/figure.ts
> +        break;
Got it. That approach makes perfect sense, I've made the necessary changes, Thanks!

2024-02-27 14:22 UTC, hokolomopo commented on tests/components/charts.test.ts
> +    dispatchCtrlKey("z");
Your helper isn't really making a difference in length/readability VS `keyDown({ key: "z", ctrlKey: true });`. I'd remove it. The `// CTRL+Z` comments also look useless, don't put a comment if the code is easy to understand 🙂

2024-03-08 16:35 UTC, rrahir requested changes

2024-03-13 07:44 UTC, rrahir commented
@robodoo r+

2024-03-13 07:44 UTC, rrahir commented
thanks a lot :)

2024-03-13 07:52 UTC, closed without merging

2024-05-14 13:41 UTC, rrahir commented on src/components/figures/figure/figure.ts
> +        break;
After a long consideration and wrecking my head on task 3868838, I would argue the exact opposite - I guess we can discuss this approach more generally with the team.
My take is the following: A component should only know about the model state, the store state (starting its introduction) as it's global, and its own state, props and provided env. A child component should not know its parent. Letting an event bubble saying "ok, the parent of my parent handles this specific event so I can let it bubble" demonstrates that the component is fully aware of the global component organization. THis means we would end up (or actually already do, I wouldn't suprised) having dependency loops (in the functional sense) in the components tree and I think its a really bad idea.