[FIX] xlsx: accelerate xlsx export
odoo/o-spreadsheet pull request #3949
Opened 2024-04-01 12:12 UTC by rrahir

Two points were identified:
- json.strignfy is slower than deepEquals (and actually wrong) ex a = {'a':2,'b':4} b = {"b": 4, 'a':2} JSON.stringify(a) === JSON.stringify(b) // false
- double call to visit the list (useless)
- findIndex looks way more efficient (on firefox at least, need to test chrome) Object.values exploration

## Description:

description of this task, what is implemented and why it is implemented that way.

Task: : [TASK_ID](https://www.odoo.com/web#id=TASK_ID&action=333&active_id=2328&model=project.task&view_type=form&cids=1&menu_id=4720)

## review checklist

- [ ] feature is organized in plugin, or UI components
- [ ] support of duplicate sheet (deep copy)
- [ ] in model/core: ranges are Range object, and can be adapted (adaptRanges)
- [ ] in model/UI: ranges are strings (to show the user)
- [ ] undo-able commands (uses this.history.update)
- [ ] multiuser-able commands (has inverse commands and transformations where needed)
- [ ] new/updated/removed commands are documented
- [ ] exportable in excel
- [ ] translations (\_t("qmsdf %s", abc))
- [ ] unit tested
- [ ] clean commented code
- [ ] track breaking changes
- [ ] doc is rebuild (npm run doc)
- [ ] status is correct in Odoo

2024-04-01 12:13 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo/o-spreadsheet/pull/3949).

2024-04-08 11:29 UTC, anhe-odoo requested changes

2024-04-08 11:29 UTC, anhe-odoo commented on src/xlsx/helpers/content_helpers.ts
> +  return propertyList.length - 1;
Can't we re-use `len` here ?
```js
propertyList[len] = property;
return len;
```
?

2024-04-08 11:53 UTC, LucasLefevre reviewed
Nice ! :+1:

2024-04-08 11:53 UTC, LucasLefevre commented on tests/__snapshots__/xlsx.test.ts.snap
> +        </border>
Do you know what causes theses changes in the snapshot ?

2024-04-08 12:04 UTC, LucasLefevre approved these changes
robodoo r+ rebase-ff

2024-04-08 12:05 UTC, robodoo commented
Merge method set to rebase and fast-forward.

2024-04-08 12:10 UTC, closed without merging