[IMP] charts: disable legend for single dataset
odoo/o-spreadsheet pull request #4600
Opened 2024-07-05 09:41 UTC by anhe-odoo

## Task Description

When drawing a chart with only one dataset, we are allowed to choose the position of the legend but no legend will appears even after changing the position. This commit aims to fix thie issue, disabling the select box allowing to change the legend position.

The chart padding has also been adapted to have more padding when there is no title/legend.

## Related Task

- Task: [4028903](https://www.odoo.com/odoo/project/2328/tasks/4028903?cids=1)

## review checklist

- [ ] feature is organized in plugin, or UI components
- [ ] support of duplicate sheet (deep copy)
- [ ] in model/core: ranges are Range object, and can be adapted (adaptRanges)
- [ ] in model/UI: ranges are strings (to show the user)
- [ ] undo-able commands (uses this.history.update)
- [ ] multiuser-able commands (has inverse commands and transformations where needed)
- [ ] new/updated/removed commands are documented
- [ ] exportable in excel
- [ ] translations (\_t("qmsdf %s", abc))
- [ ] unit tested
- [ ] clean commented code
- [ ] track breaking changes
- [ ] doc is rebuild (npm run doc)
- [ ] status is correct in Odoo

2024-07-05 09:42 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/o-spreadsheet/pull/4600.png)](https://mergebot.odoo.com/odoo/o-spreadsheet/pull/4600)

2024-07-08 07:45 UTC, hokolomopo commented on src/helpers/figures/charts/bar_chart.ts
> +  let topPadding = 25;
Maybe create a helper, copy/pasting 3 times seems a bit much :)

2024-07-10 12:13 UTC, hokolomopo commented on src/components/side_panel/chart/chart_with_axis/design_panel.xml
> -            class="o-input"
The class `legend-position-selector` doesn't seems to be used anywhere I think ?

2024-07-22 07:37 UTC, pro-odoo requested changes
Just a little detail

2024-07-22 07:37 UTC, pro-odoo commented on src/helpers/figures/charts/chart_common.ts
> +): {
```suggestion
export function computeChartPadding({
  displayTitle: boolean,
  displayLegend: boolean
}): {
```
IMO it's easier to read a call like 
```ts
padding: computeChartPadding({
    displayTitle: !!chart.title.text,
    displayLegend: legend.display !== false
}),
``` 
than 
```ts
padding: computeChartPadding(!!chart.title.text, legend.display !== false),
```

2024-07-24 11:09 UTC, hokolomopo reviewed
Maybe also add some tests on the chart padding, and It'll be good :)

2024-07-29 08:11 UTC, LucasLefevre approved these changes
robodoo r+

2024-07-29 08:19 UTC, closed without merging