[IMP] figures: add anchor to figures
odoo/o-spreadsheet pull request #5356
Opened 2024-12-16 13:15 UTC by fdamhaut

## Description:

description of this task, what is implemented and why it is implemented that way.

Task: [TASK_ID](https://www.odoo.com/odoo/2328/tasks/TASK_ID)

## review checklist

- [ ] feature is organized in plugin, or UI components
- [ ] support of duplicate sheet (deep copy)
- [ ] in model/core: ranges are Range object, and can be adapted (adaptRanges)
- [ ] in model/UI: ranges are strings (to show the user)
- [ ] undo-able commands (uses this.history.update)
- [ ] multiuser-able commands (has inverse commands and transformations where needed)
- [ ] new/updated/removed commands are documented
- [ ] exportable in excel
- [ ] translations (\_t("qmsdf %s", abc))
- [ ] unit tested
- [ ] clean commented code
- [ ] track breaking changes
- [ ] doc is rebuild (npm run doc)
- [ ] status is correct in Odoo

2024-12-16 13:15 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/o-spreadsheet/pull/5356.png)](https://mergebot.odoo.com/odoo/o-spreadsheet/pull/5356)

2025-01-28 13:52 UTC, pro-odoo reviewed
Some comments while scrolling :)

2025-01-28 13:52 UTC, pro-odoo commented on src/types/figure.ts
> +}
We use a lot `figureUI.figure.id`, this makes the code harder to read IMHO.
Also, I'm not sure about the naming of `FigureUI`
What do you think of:
```ts
export interface FigureWithDomCoordinates extends Figure {
  domCoordinates: DOMCoordinates;
}
```

2025-01-28 13:52 UTC, pro-odoo commented on demo/data.js
> +<<<<<<< HEAD
A little rebase is needed :)
I made a PR to update demo data in v25 (https://github.com/odoo/o-spreadsheet/pull/5563/files) so you can remove the next commit. Then you can add a commit with an update to v26 (it will make the diff lower).
Thanks !

2025-01-28 13:52 UTC, pro-odoo commented on src/types/commands.ts
> +export interface CreateImageOverCommand extends SheetDependentCommand, SubFigureCommand {
This will require an upgrade script in odoo. See here for an exemple:
https://github.com/odoo/upgrade/blob/master/migrations/spreadsheet_edition/saas~17.5.1.0/pre-migrate.py

2025-01-28 14:00 UTC, LucasLefevre reviewed
Also a partial review

2025-02-03 15:36 UTC, fdamhaut commented on src/components/side_panel/chart/building_blocks/general_design/general_design_editor.xml
> +        <Section title.translate="Position">
This was due to discussion with VSC, as both excel and google allow the user to choose between those 2 behaviours

2025-03-07 13:55 UTC, hokolomopo reviewed
Xlsx import/export is totally broken, all the figures are on the top-left of the sheets :x

2025-03-07 13:55 UTC, hokolomopo commented on src/types/commands.ts
> +  offset?: PixelPosition;
why optional ?

2025-03-07 13:55 UTC, hokolomopo commented on src/clipboard_handlers/image_clipboard.ts
> +    this.dispatch("SELECT_FIGURE", { figureId: figureId });
```suggestion
    this.dispatch("SELECT_FIGURE", { figureId });
```
there's probably other places in the code with this

2025-03-07 13:55 UTC, hokolomopo commented on src/types/commands.ts
> +  anchor?: Position;
I don't think `anchor` is transformed if someone were to add a row at the same time you add a figure. Would work w/o needing `ot_specific` stuff if you extends `PositionDependentCommand` and remove the anchor.

2025-03-07 13:55 UTC, hokolomopo commented on tests/figures/image/image_plugin.test.ts
> +    createImage(model, { id: imageId, definition });
why those changes ? It's still a figureId as far as I can see

2025-03-07 13:55 UTC, hokolomopo commented on tests/figures/chart/menu_item_insert_chart.test.ts
> +      row: 14,
All the changes to this test file are sus'. What are these hardcoded values and where do they come from ? I get it's supposed to be the center of the screen, but why do we need to hard code them instead of computing it now ? And why is another test `expect({ x: figureUI.x, y: figureUI.y }).toStrictEqual` now needed ? Is the payload test not enough ? I'm a bit confused.

2025-03-07 13:55 UTC, hokolomopo commented on tests/figures/chart/menu_item_insert_chart.test.ts
> +    expect({ x: figureUI.x, y: figureUI.y }).toStrictEqual({
```suggestion
    expect(model.getters.getVisibleFigures()[0]).toMatchObject({
```

2025-03-07 13:55 UTC, hokolomopo commented on tests/figures/figure_component.test.ts
> +      [{ wheelX: 40, wheelY: 0 }], // scroll out of original viewport
nitpick: variable names `wheelX` which looks like DOM event parameters being in `HeaderOffset` instead of `Pixel` is a bit confusing. Just add `additionalOffsetX` or keep wheelX and do things like `Math.floor(wheelX /DEFAULT_CELL_HEIGHT)` to compute the anchor/offset if you want to test those

2025-03-17 15:51 UTC, rrahir reviewed
Hello 👋  

Mainly details and maybe one or two points that could be reworked for readability/ simplicity.

I haven't read the tests yet.

2025-03-17 15:51 UTC, rrahir commented on src/plugins/ui_stateful/sheetview.ts
> +    const colIndex = this.getColIndex(x);
I have a hard time understanding the implementation :/
We should also find a clearer name imho

2025-03-17 15:51 UTC, rrahir commented on src/plugins/ui_stateful/sheetview.ts
> +      y -= this.getters.getUserRowSize(sheetId, i) ?? DEFAULT_CELL_HEIGHT;
```suggestion
      y -= this.getters.getRowSize(sheetId, i);
```

2025-03-17 15:51 UTC, rrahir commented on src/plugins/ui_stateful/sheetview.ts
> +  getFigureUI(sheetId: string, figure: Figure): FigureUI {
```suggestion
  getFigureUI(sheetId: UID, figure: Figure): FigureUI {
```

2025-03-17 15:51 UTC, rrahir commented on src/plugins/ui_stateful/sheetview.ts
> +    const { x: offsetCorrectionX, y: offsetCorrectionY } = this.getMainViewportCoordinates();
useless diff

2025-03-17 15:51 UTC, rrahir commented on src/plugins/ui_stateful/sheetview.ts
> +  getPositionAnchorOffset(sheetId: string, position: PixelPosition): AnchorOffset {
I would suggest the follwing implementation that allows to avoid a certain number of new helpers:
I haven't tested it, but its to give the general idea. I would bet that it misses a scroll correction somewhere ^^ 
 ```typescript
const col = this.getColIndex(position.x) // find the cell we are part of
const row = this.getRowIndex(position.y)
const {x, y} = this.getRect(positionToZone({col, row})) // get the topLeft point of the cell (even if it's partially hidden by the scroll)

return {
      anchor: {col ,row},
      offset: {
        x: position.x - x,
        y: position.y - y,
      },
    };

2025-03-21 14:48 UTC, rrahir reviewed
👋 New wave of comments, apparently  I missed several things at my first pas, i'll need to get back to it again and have a closer look at the drag and drop figure changes ;-)

2025-03-21 14:48 UTC, rrahir commented on src/components/figures/figure_container/figure_container.ts
> +      figureUI.x += initialScrollPosition.scrollX;
I think the previous approach that would create a new object was better because here , you change the values in place but the object is passed as a props, so you actually change a props in place.

Was there a specific reason to get rid of `internalFigureToScreen` and its friends? I found the intention clearer with it (subjective af) but I might miss something related to the new anchor

2025-03-21 14:53 UTC, rrahir commented
@fdamhaut I forgot a point, we should have some tests that cover the functional issues I mentionned in the task pad (deleting the anchor header and the "MOVE_COLUMNS_ROWS" issue

2025-03-24 09:39 UTC, fdamhaut commented
> @fdamhaut I forgot a point, we should have some tests that cover the functional issues I mentionned in the task pad (deleting the anchor header and the "MOVE_COLUMNS_ROWS" issue

I already added some test in figures_plugin.test for that L457-830

2025-03-24 10:38 UTC, fdamhaut commented on src/types/commands.ts
> +  figureId: UID;
More than alerting the dev, the goal is harmonizing command to have a similar structure. And from having either "id" or "figureId", i think the more explicit option is the best. (+ It's more like the rest of the command, sheet always use "sheetId", Pivot almost always use "pivotId",...)

2025-03-24 11:50 UTC, fdamhaut commented on src/components/figures/figure_container/figure_container.ts
> +      figureUI.x += initialScrollPosition.scrollX;
> Was there a specific reason to get rid of internalFigureToScreen and its friends? I found the intention clearer with it (subjective af) but I might miss something related to the new anchor
Here the code only move the figure coordinate if it's part of the frozen pane viewport so that is doesn't teleport to their "true" position, it's not really related to "internal -> screen" old behaviour.
However, i will isolate the resulting code in a method to be more explicit :+1:

2025-03-26 13:05 UTC, rrahir commented
> figures_plugin.test

SOrry I completely missed it :'(

2025-04-08 12:48 UTC, rrahir requested changes
👋  Some small changes and a rebase and I think we're good to go :)

2025-04-08 12:48 UTC, rrahir commented on src/plugins/ui_stateful/selection.ts
> +          col: figure.row,
```suggestion
          col: figure.col,
```
maybe a small test ^^

2025-04-08 12:48 UTC, rrahir commented on src/plugins/ui_stateful/sheetview.ts
> +      rowStart -= this.getters.getColSize(sheetId, row - 1);
```suggestion
      rowStart -= this.getters.getRowSize(sheetId, row - 1);
```
or probably getUserRowSize ?

2025-04-14 11:29 UTC, rrahir commented
@robodoo r+

2025-04-14 11:43 UTC, closed without merging